### ISSUE TITLE
LED strip model example?

### ISSUE THREAD

**Issue by tomazbracic** [a-maze-d/fledex#4]
Hi, 

would it be possible to name few products, that you can control with this? Which one did you use? I would like to purchase one on Amazon.de, but you rarely see chip information. 

Just a model info of LED strip you used. I would too, like to play with my son with this and nerves. 

Thanks in advance. 

Kind regards,
Tomaz

**Comment by a-maze-d** [comment]
You should find all the necessary information here (I added that info recently):
https://github.com/a-maze-d/fledex/blob/main/docs/hardware.md

The ws2801 strips are a) a bit more expensive and b) a bit harder to get hold of, but the above mentioned document does have a link to Amazon.

It should be quite easy to create a driver to control other type of strips too. You can find quite good examples like this one:
https://tutorials-raspberrypi.com/connect-control-raspberry-pi-ws2812-rgb-led-strips/
I don't have such a strip (yet), and therefore there is no driver for it (yet), but feel free to contribute. The only thing you need to do is to implement this simple interface (the heavy lifting is probably done through the circuits library which makes this very easy):
https://github.com/a-maze-d/fledex/blob/main/lib/fledex/driver/interface.ex

Note: I do plan to make some changes on how to configure drivers, but the one for ws2801 can be found here:
https://github.com/a-maze-d/fledex/blob/main/lib/fledex/driver/impl/spi.ex

I hope this helps

**Comment by a-maze-d** [comment]
@tomazbracic Did that answer your question? Is the documentation sufficient, or any ideas/suggestions on how to improve it?

If I don't hear back, I'll assume we can close this issue

**Comment by a-maze-d** [comment]
Closing now this issue. Feel free to open it again is something is missing
